// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: todo.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type CreateTodoParams struct {
	ID          uuid.UUID
	UserID      uuid.UUID
	Title       string
	Description sql.NullString
	Completed   bool
}

func (q *Queries) CreateTodo(ctx context.Context, arg CreateTodoParams) (Todo, error) {
	const query = `
		INSERT INTO todos (id, user_id, title, description, completed)
		VALUES ($1, $2, $3, $4, $5)
		RETURNING id, user_id, title, description, completed, created_at, updated_at
	`
	row := q.db.QueryRow(ctx, query, arg.ID, arg.UserID, arg.Title, arg.Description, arg.Completed)

	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetTodoByID(ctx context.Context, id uuid.UUID) (Todo, error) {
	const query = `
		SELECT id, user_id, title, description, completed, created_at, updated_at
		FROM todos
		WHERE id = $1
		LIMIT 1
	`
	row := q.db.QueryRow(ctx, query, id)

	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) ListTodosByUserID(ctx context.Context, userID uuid.UUID) ([]Todo, error) {
	const query = `
		SELECT id, user_id, title, description, completed, created_at, updated_at
		FROM todos
		WHERE user_id = $1
		ORDER BY created_at DESC
	`
	rows, err := q.db.Query(ctx, query, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type ListTodosByUserIDAndStatusParams struct {
	UserID    uuid.UUID
	Completed bool
}

func (q *Queries) ListTodosByUserIDAndStatus(ctx context.Context, arg ListTodosByUserIDAndStatusParams) ([]Todo, error) {
	const query = `
		SELECT id, user_id, title, description, completed, created_at, updated_at
		FROM todos
		WHERE user_id = $1 AND completed = $2
		ORDER BY created_at DESC
	`
	rows, err := q.db.Query(ctx, query, arg.UserID, arg.Completed)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []Todo
	for rows.Next() {
		var i Todo
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Title,
			&i.Description,
			&i.Completed,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

type UpdateTodoParams struct {
	ID          uuid.UUID
	Title       sql.NullString
	Description sql.NullString
	Completed   sql.NullBool
}

func (q *Queries) UpdateTodo(ctx context.Context, arg UpdateTodoParams) (Todo, error) {
	const query = `
		UPDATE todos
		SET
			title = COALESCE($2, title),
			description = COALESCE($3, description),
			completed = COALESCE($4, completed),
			updated_at = NOW()
		WHERE id = $1
		RETURNING id, user_id, title, description, completed, created_at, updated_at
	`
	row := q.db.QueryRow(ctx, query, arg.ID, arg.Title, arg.Description, arg.Completed)

	var i Todo
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Title,
		&i.Description,
		&i.Completed,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) DeleteTodo(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `DELETE FROM todos WHERE id = $1`, id)
	return err
}

func (q *Queries) CountTodosByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	const query = `SELECT COUNT(*) FROM todos WHERE user_id = $1`
	row := q.db.QueryRow(ctx, query, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

func (q *Queries) CountCompletedTodosByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	const query = `SELECT COUNT(*) FROM todos WHERE user_id = $1 AND completed = true`
	row := q.db.QueryRow(ctx, query, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}
