// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: user.sql

package db

import (
	"context"
	"database/sql"

	"github.com/google/uuid"
)

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	const query = `
		INSERT INTO users (id, email, password_hash, name)
		VALUES ($1, $2, $3, $4)
		RETURNING id, email, password_hash, name, created_at, updated_at
	`
	row := q.db.QueryRow(ctx, query, arg.ID, arg.Email, arg.PasswordHash, arg.Name)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	const query = `
		SELECT id, email, password_hash, name, created_at, updated_at
		FROM users
		WHERE email = $1
		LIMIT 1
	`
	row := q.db.QueryRow(ctx, query, email)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	const query = `
		SELECT id, email, password_hash, name, created_at, updated_at
		FROM users
		WHERE id = $1
		LIMIT 1
	`
	row := q.db.QueryRow(ctx, query, id)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

type UpdateUserParams struct {
	ID    uuid.UUID
	Name  sql.NullString
	Email sql.NullString
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	const query = `
		UPDATE users
		SET
			name = COALESCE($2, name),
			email = COALESCE($3, email),
			updated_at = NOW()
		WHERE id = $1
		RETURNING id, email, password_hash, name, created_at, updated_at
	`
	row := q.db.QueryRow(ctx, query, arg.ID, arg.Name, arg.Email)

	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, `DELETE FROM users WHERE id = $1`, id)
	return err
}

type ListUsersParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	const query = `
		SELECT id, email, password_hash, name, created_at, updated_at
		FROM users
		ORDER BY created_at DESC
		LIMIT $1 OFFSET $2
	`
	rows, err := q.db.Query(ctx, query, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()

	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PasswordHash,
			&i.Name,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
